config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework.documentation import include_docs_urls
from rest_framework.documentation import get_schemajs_view
from rest_framework.authtoken.views import obtain_auth_token


schemajs_view = get_schemajs_view(title='IllumiDesk API')


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('illumidesk.web.urls')),
    path('api/', include('config.api_router')),
    path('auth-token/', obtain_auth_token),
    path('accounts/', include('allauth.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    path('docs/', include_docs_urls(title='IllumiDesk API Docs')),
    path('illumidesk/', include('illumidesk.examples.urls')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    path('stripe/', include('djstripe.urls', namespace='djstripe')),
    path('subscriptions/', include('illumidesk.subscriptions.urls')),
    path('teams/', include('illumidesk.teams.urls')),
    path('users/', include('illumidesk.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

illumidesk/teams/urls.py
from django.urls import path
from . import views

from rest_framework import routers


app_name = 'teams'

urlpatterns = [
    path('', views.manage_teams, name='manage_teams'),
    path('list/', views.list_teams, name='list_teams'),
    path('create/', views.create_team, name='create_team'),
    path('<slug:team_slug>/manage/', views.manage_team, name='manage_team'),
    path('invitation/<slug:invitation_id>/', views.accept_invitation, name='accept_invitation'),
]

# drf config
router = routers.DefaultRouter()
router.register(r'api/teams', views.TeamViewSet)
router.register(r'api/invitations', views.InvitationViewSet)
urlpatterns += router.urls

illumidesk/users/urls.py
from django.urls import path

from illumidesk.users.views import user_detail_view
from illumidesk.users.views import user_redirect_view
from illumidesk.users.views import user_update_view

from . import views


app_name = 'users'
urlpatterns = [
    path(r'profile/', views.profile, name='user_profile'),
    path(r'profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
]

illumidesk/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'web'

urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'a/<slug:team_slug>', views.team_home, name='team_home'),
    path(r'a/<slug:team_slug>/manage/', views.team_admin_home, name='team_admin'),
    path(r'terms', TemplateView.as_view(template_name="web/terms.html"), name='terms'),
]

illumidesk/components/models.py
from django.db.models import DateTimeField
from django.db.models import Model


class IllumiDeskBaseModel(Model):
    """
    Base model that includes default created / updated timestamps.
    """
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)

    class Meta:
        abstract = True

app-backend/appdj/teams/views.py
from django.conf import settings
from rest_framework import viewsets, status, permissions
from rest_framework.response import Response
from rest_framework.decorators import api_view

from appdj.base.views import LookupByMultipleFields
from appdj.base.utils import get_object_or_404
from .models import Team, Group
from .serializers import TeamSerializer, GroupSerializer, GroupUserSerializer
from .permissions import GroupPermission


class TeamViewSet(LookupByMultipleFields, viewsets.ModelViewSet):
    queryset = Team.objects.all()
    serializer_class = TeamSerializer
    lookup_url_kwarg = 'team'

    def get_queryset(self):
        qs = super().get_queryset()
        version = self.kwargs.get('version', settings.DEFAULT_VERSION)
        if self.request.META['PATH_INFO'].startswith(f'/{version}/me/'):
            return qs.filter(groups__user=self.request.user)
        return qs


class GroupViewSet(LookupByMultipleFields, viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = (permissions.IsAuthenticated, GroupPermission)
    lookup_url_kwarg = 'group'

    def get_queryset(self):
        team = Team.objects.tbs_get(self.kwargs['team_team'])
        return super().get_queryset().filter(team=team)


def _user_group_action(action, request, **kwargs):
    group = get_object_or_404(Group, kwargs['group'])
    serializer = GroupUserSerializer(request.data)
    if serializer.is_valid():
        act = getattr(group.user_set, action)
        act(serializer.data['user'])
        return Response({'message': 'OK'})
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['post'])
def add_user_to_group(request, **kwargs):
    return _user_group_action('add', request, **kwargs)


@api_view(['post'])
def remove_user_from_group(request, **kwargs):
    return _user_group_action('remove', request, **kwargs)

illumidesk/subscriptions/views.py
import json

import djstripe
from djstripe.enums import PlanInterval
from djstripe.models import Product
from djstripe import settings as djstripe_settings

import stripe

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import mail_admins
from django.db import transaction
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_POST

from illumidesk.decorators import catch_stripe_errors
from illumidesk.teams.decorators import team_admin_required
from illumidesk.teams.decorators import login_and_team_required
from illumidesk.teams.models import Team
from illumidesk.utils.subscriptions import get_friendly_currency_amount

from .decorators import redirect_subscription_errors
from .metadata import get_active_products_with_metadata
from .metadata import get_product_and_metadata_for_subscription
from .metadata import ACTIVE_PLAN_INTERVALS
from .metadata import get_active_plan_interval_metadata


@redirect_subscription_errors
@login_required
def subscription(request, subscription_holder=None):
    subscription_holder = subscription_holder if subscription_holder else request.user
    if subscription_holder.has_active_subscription():
        return _view_subscription(request, subscription_holder)
    else:
        return _upgrade_subscription(request, subscription_holder)


def _view_subscription(request, subscription_holder):
    """
    Show user's active subscription
    """
    assert subscription_holder.has_active_subscription()
    return render(request, 'subscriptions/view_subscription.html', {
        'active_tab': 'subscription',
        'subscription': subscription_holder.active_stripe_subscription,
        'friendly_payment_amount': get_friendly_currency_amount(
            subscription_holder.active_stripe_subscription.plan.amount,
            subscription_holder.active_stripe_subscription.plan.currency,
        ),
        'product': get_product_and_metadata_for_subscription(subscription_holder.active_stripe_subscription),
    })


def _upgrade_subscription(request, subscription_holder):
    """
    Show subscription upgrade form / options.
    """
    assert not subscription_holder.has_active_subscription()

    active_products = list(get_active_products_with_metadata())
    default_products = [p for p in active_products if p.metadata.is_default]
    default_product = default_products[0] if default_products else active_products[0]

    def _to_dict(product_with_metadata):
        # for now, just serialize the minimum amount of data needed for the front-end
        product_data = {}
        if PlanInterval.year in ACTIVE_PLAN_INTERVALS:
            product_data['annual_plan'] = {
                'stripe_id': product_with_metadata.annual_plan.id,
                'payment_amount': get_friendly_currency_amount(product_with_metadata.annual_plan.amount,
                                                               product_with_metadata.annual_plan.currency),
                'monthly_amount': get_friendly_currency_amount(product_with_metadata.annual_plan.amount / 12,
                                                               product_with_metadata.annual_plan.currency),
                'interval': PlanInterval.year,  # set to month because we're dividing price by 12
            }
        if PlanInterval.month in ACTIVE_PLAN_INTERVALS:
            product_data['monthly_plan'] = {
                'stripe_id': product_with_metadata.monthly_plan.id,
                'payment_amount': get_friendly_currency_amount(product_with_metadata.monthly_plan.amount,
                                                               product_with_metadata.monthly_plan.currency),
                'monthly_amount': get_friendly_currency_amount(product_with_metadata.monthly_plan.amount,
                                                               product_with_metadata.monthly_plan.currency),
                'interval': PlanInterval.month,
            }
        return product_data

    return render(request, 'subscriptions/upgrade_subscription.html', {
        'active_tab': 'subscription',
        'stripe_api_key': djstripe_settings.STRIPE_PUBLIC_KEY,
        'default_product': default_product,
        'active_products': active_products,
        'active_products_json': {str(p.stripe_id): _to_dict(p) for p in active_products},
        'active_plan_intervals': get_active_plan_interval_metadata(),
        'default_to_annual': ACTIVE_PLAN_INTERVALS[0] == PlanInterval.year,
        'subscription_urls': _get_subscription_urls(subscription_holder),
        'payment_metadata': _get_payment_metadata_from_request(request),
    })


def _get_payment_metadata_from_request(request):
    return {
        'user_id': request.user.id,
        'user_email': request.user.email,
        'team_id': request.team.id,
    }


@login_required
def subscription_success(request):
    return _subscription_success(request, request.user)

def _subscription_success(request, subscription_holder):
    stripe.api_key = djstripe_settings.STRIPE_SECRET_KEY
    if not subscription_holder.has_active_subscription():
        subscription = subscription_holder.stripe_subscription
        if not subscription:
            messages.error(
                request,
               "Oops, it looks like there was a problem processing your payment. "
               "Please try again, or get in touch if you think this is a mistake."
            )
        else:
            # 3D-Secure workflow hopefully completed successfully,
            # re-sync the subscription and hopefully it will be active
            subscription.sync_from_stripe_data(subscription.api_retrieve())

    if subscription_holder.has_active_subscription():
        subscription_name = get_product_and_metadata_for_subscription(
            subscription_holder.active_stripe_subscription
        ).metadata.name
        messages.success(request, f"You've successfully signed up for {subscription_name}. "
                                  "Thanks so much for the support!")
        # notify admins when someone signs up
        mail_admins(
            subject=f"Hooray! Someone just signed up for a {subscription_name} subscription!",
            message="Email: {}".format(request.user.email),
            fail_silently=True,
        )
    
    assert isinstance(subscription_holder, Team)
    redirect = reverse('subscriptions:team_subscription_details', args=[subscription_holder.slug])
    
    return HttpResponseRedirect(redirect)


@login_required
@require_POST
@catch_stripe_errors
@transaction.atomic
def create_customer(request, subscription_holder=None):
    """
    Create a Stripe Customer and Subscription object and map them onto the subscription_holder

    Expects the inbound POST data to look something like this:
    {
        'email': 'cory@example.com',
        'userId': '23',
        'payment_method': 'pm_1GGgZaIYTEadrA0y0tthZ5UH'
    }
    """
    subscription_holder = subscription_holder if subscription_holder else request.user
    request_body = json.loads(request.body.decode('utf-8'))
    user_id = int(request_body['user_id'])
    email = request_body['user_email']
    assert request.user.id == user_id
    assert request.user.email == email

    assert isinstance(subscription_holder, Team)
    team_id = int(request_body['team_id'])
    assert request.team.id == team_id
    
    payment_method = request_body['payment_method']
    plan_id = request_body['plan_id']
    stripe.api_key = djstripe_settings.STRIPE_SECRET_KEY

    # first sync payment method to local DB to workaround https://github.com/dj-stripe/dj-stripe/issues/1125
    payment_method_obj = stripe.PaymentMethod.retrieve(payment_method)
    djstripe.models.PaymentMethod.sync_from_stripe_data(payment_method_obj)

    # create customer objects
    # This creates a new Customer in stripe and attaches the default PaymentMethod in one API call.
    customer = stripe.Customer.create(
      payment_method=payment_method,
      email=email,
      invoice_settings={
        'default_payment_method': payment_method,
      },
    )

    djstripe_customer = djstripe.models.Customer.sync_from_stripe_data(customer)

    # create subscription
    subscription = stripe.Subscription.create(
      customer=customer.id,
      items=[
        {
          'plan': plan_id,
        },
      ],
      expand=['latest_invoice.payment_intent'],
    )
    djstripe_subscription = djstripe.models.Subscription.sync_from_stripe_data(subscription)

    # customer always is associated with the user
    request.user.customer = djstripe_customer

    subscription_holder.subscription = djstripe_subscription
    if subscription_holder != request.user:
        subscription_holder.save()

    request.user.save()

    data = {
        'customer': customer,
        'subscription': subscription
    }
    return JsonResponse(
        data=data,
    )

def _get_subscription_urls(subscription_holder):
    # get URLs for subscription helpers
    url_bases = [
        'subscription_details',
        'create_customer',
        'subscription_success',
        'subscription_demo',
        'subscription_gated_page',
    ]

    def _construct_url(base):
        return reverse(f'subscriptions:team_{base}', args=[subscription_holder.slug])
        

    return {
        url_base: _construct_url(url_base) for url_base in url_bases
    }


@login_required
def subscription_demo(request, subscription_holder=None):
    subscription_holder = subscription_holder if subscription_holder else request.user
    return render(request, 'subscriptions/demo.html', {
        'active_tab': 'subscription_demo',
        'subscription': subscription_holder.active_stripe_subscription,
        'product': get_product_and_metadata_for_subscription(
            subscription_holder.active_stripe_subscription
        ),

illumidesk/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from django.contrib.auth import get_user_model

from .serializers import UserSerializer


User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

illumidesk/templates/teams/accept_invite.html
{% extends "illumidesk/base.html" %}
{% load static %}
{% load i18n %}
{% block body %}
<section class="section container">
    <div class="columns">
        <div class="column is-one-third">
            <img src="{% static 'images/illumidesk/undraw/undraw_lighthouse.svg' %}" alt="Welcome!">
        </div>
        <div id="tagline" class="column">
            <h1 class="title is-size-2">Accept Invitation?</h1>
            <h2 class="subtitle is-size-4">
                You've been invited to join {{ invitation.team.name }}
                by {{ invitation.invited_by.get_display_name }}.
            </h2>
            {% if request.user.is_authenticated and request.user == invitation.email %}
                <p class="buttons">
                    <a class="button is-primary is-large" href="{% url 'account_signup' %}?invitation_id={{ invitation.id }}">
                        Accept
                    </a>
                </p>
            {% elif request.user.is_authenticated %}
                <p class="warning">
                     This invitation was sent to {{ invitation.email }} but you're logged in as {{ request.user.email }}.
                     What would you like to do?
                </p>
                <p class="buttons">
                    <a class="button is-primary is-large" href="{% url 'account_signup' %}?invitation_id={{ invitation.id }}">
                        Accept as {{ request.user.email }}
                    </a>
                    <a class="button is-primary is-large is-outlined" href="{% url 'account_signup' %}?invitation_id={{ invitation.id }}">
                        Sign out
                    </a>
                </p>
            {% else %}
                <p class="buttons">
                    <a class="button is-primary is-large" href="{% url 'account_signup' %}?invitation_id={{ invitation.id }}">
                        Create Account to Accept
                    </a>
                </p>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

illumidesk/templates/teams/list_teams.html
{% extends "illumidesk/app/app_base.html" %}
{% load static %}
{% block app %}
{% if teams %}
<h1 class="title is-size-4">Your Teams</h1>
<table class="table is-striped is-fullwidth">
    <thead>
    <tr>
        <th>Name</th>
    </tr>
    </thead>
    <tbody>
    {% for team in teams %}
    <tr>
        <td><a href="{% url 'teams:manage_team' team.slug %}">{{team.name}}</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a class="button is-primary is-outlined" href="{% url 'teams:create_team' %}">
    <span class="icon is-small"><i class="fa fa-plus"></i></span>
    <span>New Team</span>
</a>
{% else %}
<div id="dashboard-content">
    <div class="columns">
        <div class="column is-one-third">
            <img alt="Nothing Here" src="{% static 'images/illumidesk/undraw/undraw_team.svg' %}">
        </div>
        <div class="column is-two-thirds">
            <h1 class="title is-4">No Teams Yet!</h1>
            <h2 class="subtitle">Create your first team below to get started.</h2>
            <p>
                <a class="button is-primary" href="{% url 'teams:create_team' %}">
                    <span class="icon is-small"><i class="fa fa-plus"></i></span>
                    <span>Create Team</span>
                </a>
            </p>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

illumidesk/templates/teams/manage_team.html
{% extends "illumidesk/app/app_base.html" %}
{% load static %}
{% load i18n %}
{% block app %}
<section class="app-card">
    <h1 class="title is-size-4">
        {% if create %}
            {% trans "Create Team" %}
        {% else %}
            {% trans "Edit Team Details" %}
        {% endif %}
    </h1>
    <form method="post">
        {% csrf_token %}
        <div class="field">
          <label class="label">{% trans "Name" %}</label>
          <div class="control">
            {{ form.name }}
          </div>
          {{ form.name.errors }}
        </div>
        <div class="field">
          <label class="label">{% trans "Team ID" %}</label>
          <div class="control">
            {{ form.slug }}
          </div>
          {{ form.slug.errors }}
        </div>
        <div class="field is-grouped">
            <div class="control">
                <input class="button is-primary" type="submit" value="{% trans 'Save' %}">
            </div>
        </div>
    </form>
</section>
{% if not create %}
    <div id="team-content"></div>
{% endif %}
{% endblock %}
{% block page_js %}
{# NOTE: the rest framework imports must precede the react bundle #}
<script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
<script src="{% url 'api_schemajs' %}"></script>
<script src="{% static 'js/teams-bundle.js' %}"></script>
{% endblock %}

illumidesk/templates/teams/teams.html
{% extends "illumidesk/app/app_base.html" %}
{% load static %}
{% load i18n %}
{% block app %}
  <div id="team-content"></div>
{% endblock %}
{% block page_js %}
{# NOTE: the rest framework imports must precede the react bundle #}
<script type="application/javascript">
    // initialize any page specific stuff here
    // static files that are used by the page javascript.
    var STATIC_FILES = {
        'undraw_team': "{% static 'images/illumidesk/undraw/undraw_team.svg' %}",
    };
    {# var teamSlug = '{{ team.slug }}'; #}
</script>
<script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
<script src="{% url 'api_schemajs' %}"></script>
<script src="{% static 'js/teams-bundle.js' %}"></script>
{% endblock %}