config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework.documentation import include_docs_urls
from rest_framework.documentation import get_schemajs_view
from rest_framework.authtoken.views import obtain_auth_token


schemajs_view = get_schemajs_view(title='IllumiDesk API')


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('illumidesk.web.urls')),
    path('api/', include('config.api_router')),
    path('auth-token/', obtain_auth_token),
    path('accounts/', include('allauth.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    path('docs/', include_docs_urls(title='IllumiDesk API Docs')),
    path('illumidesk/', include('illumidesk.examples.urls')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    path('stripe/', include('djstripe.urls', namespace='djstripe')),
    path('subscriptions/', include('illumidesk.subscriptions.urls')),
    path('teams/', include('illumidesk.teams.urls')),
    path('users/', include('illumidesk.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

illumidesk/subscriptions/urls.py
from django.urls import path

from . import views


app_name = 'subscriptions'
urlpatterns = [

    # team-specific URLs
    # todo: it would be better if these matched the /a/team-slug/subscription pattern of other pages
    path('team/<slug:team_slug>/', views.team_subscription, name='team_subscription_details'),
    path('team/<slug:team_slug>/subscription_success/',
         views.team_subscription_success, name='team_subscription_success'),
    path('team/<slug:team_slug>/demo/',
         views.team_subscription_demo, name='team_subscription_demo'),
    path('team/<slug:team_slug>/subscription-gated-page/',
         views.team_subscription_gated_page, name='team_subscription_gated_page'),
    path('team/<slug:team_slug>/api/create_customer/',
         views.team_create_customer, name='team_create_customer'),
]

illumidesk/teams/urls.py
from django.urls import path
from . import views

from rest_framework import routers


app_name = 'teams'

urlpatterns = [
    path('', views.manage_teams, name='manage_teams'),
    path('list/', views.list_teams, name='list_teams'),
    path('create/', views.create_team, name='create_team'),
    path('<slug:team_slug>/manage/', views.manage_team, name='manage_team'),
    path('invitation/<slug:invitation_id>/', views.accept_invitation, name='accept_invitation'),
]

# drf config
router = routers.DefaultRouter()
router.register(r'api/teams', views.TeamViewSet)
router.register(r'api/invitations', views.InvitationViewSet)
urlpatterns += router.urls

illumidesk/users/urls.py
from django.urls import path

from illumidesk.users.views import user_detail_view
from illumidesk.users.views import user_redirect_view
from illumidesk.users.views import user_update_view

from . import views


app_name = 'users'
urlpatterns = [
    path(r'profile/', views.profile, name='user_profile'),
    path(r'profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
]

illumidesk/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'web'

urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'a/<slug:team_slug>', views.team_home, name='team_home'),
    path(r'a/<slug:team_slug>/manage/', views.team_admin_home, name='team_admin'),
    path(r'terms', TemplateView.as_view(template_name="web/terms.html"), name='terms'),
]

illumidesk/subscriptions/views.py
import json

import djstripe
from djstripe.enums import PlanInterval
from djstripe.models import Product
from djstripe import settings as djstripe_settings

import stripe

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import mail_admins
from django.db import transaction
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_POST

from illumidesk.decorators import catch_stripe_errors
from illumidesk.teams.decorators import team_admin_required
from illumidesk.teams.decorators import login_and_team_required
from illumidesk.teams.models import Team
from illumidesk.utils.subscriptions import get_friendly_currency_amount

from .decorators import redirect_subscription_errors
from .metadata import get_active_products_with_metadata
from .metadata import get_product_and_metadata_for_subscription
from .metadata import ACTIVE_PLAN_INTERVALS
from .metadata import get_active_plan_interval_metadata


@redirect_subscription_errors
@login_required
def subscription(request, subscription_holder=None):
    subscription_holder = subscription_holder if subscription_holder else request.user
    if subscription_holder.has_active_subscription():
        return _view_subscription(request, subscription_holder)
    else:
        return _upgrade_subscription(request, subscription_holder)


def _view_subscription(request, subscription_holder):
    """
    Show user's active subscription
    """
    assert subscription_holder.has_active_subscription()
    return render(request, 'subscriptions/view_subscription.html', {
        'active_tab': 'subscription',
        'subscription': subscription_holder.active_stripe_subscription,
        'friendly_payment_amount': get_friendly_currency_amount(
            subscription_holder.active_stripe_subscription.plan.amount,
            subscription_holder.active_stripe_subscription.plan.currency,
        ),
        'product': get_product_and_metadata_for_subscription(subscription_holder.active_stripe_subscription),
    })


def _upgrade_subscription(request, subscription_holder):
    """
    Show subscription upgrade form / options.
    """
    assert not subscription_holder.has_active_subscription()

    active_products = list(get_active_products_with_metadata())
    default_products = [p for p in active_products if p.metadata.is_default]
    default_product = default_products[0] if default_products else active_products[0]

    def _to_dict(product_with_metadata):
        # for now, just serialize the minimum amount of data needed for the front-end
        product_data = {}
        if PlanInterval.year in ACTIVE_PLAN_INTERVALS:
            product_data['annual_plan'] = {
                'stripe_id': product_with_metadata.annual_plan.id,
                'payment_amount': get_friendly_currency_amount(product_with_metadata.annual_plan.amount,
                                                               product_with_metadata.annual_plan.currency),
                'monthly_amount': get_friendly_currency_amount(product_with_metadata.annual_plan.amount / 12,
                                                               product_with_metadata.annual_plan.currency),
                'interval': PlanInterval.year,  # set to month because we're dividing price by 12
            }
        if PlanInterval.month in ACTIVE_PLAN_INTERVALS:
            product_data['monthly_plan'] = {
                'stripe_id': product_with_metadata.monthly_plan.id,
                'payment_amount': get_friendly_currency_amount(product_with_metadata.monthly_plan.amount,
                                                               product_with_metadata.monthly_plan.currency),
                'monthly_amount': get_friendly_currency_amount(product_with_metadata.monthly_plan.amount,
                                                               product_with_metadata.monthly_plan.currency),
                'interval': PlanInterval.month,
            }
        return product_data

    return render(request, 'subscriptions/upgrade_subscription.html', {
        'active_tab': 'subscription',
        'stripe_api_key': djstripe_settings.STRIPE_PUBLIC_KEY,
        'default_product': default_product,
        'active_products': active_products,
        'active_products_json': {str(p.stripe_id): _to_dict(p) for p in active_products},
        'active_plan_intervals': get_active_plan_interval_metadata(),
        'default_to_annual': ACTIVE_PLAN_INTERVALS[0] == PlanInterval.year,
        'subscription_urls': _get_subscription_urls(subscription_holder),
        'payment_metadata': _get_payment_metadata_from_request(request),
    })


def _get_payment_metadata_from_request(request):
    return {
        'user_id': request.user.id,
        'user_email': request.user.email,
        'team_id': request.team.id,
    }


@login_required
def subscription_success(request):
    return _subscription_success(request, request.user)

def _subscription_success(request, subscription_holder):
    stripe.api_key = djstripe_settings.STRIPE_SECRET_KEY
    if not subscription_holder.has_active_subscription():
        subscription = subscription_holder.stripe_subscription
        if not subscription:
            messages.error(
                request,
               "Oops, it looks like there was a problem processing your payment. "
               "Please try again, or get in touch if you think this is a mistake."
            )
        else:
            # 3D-Secure workflow hopefully completed successfully,
            # re-sync the subscription and hopefully it will be active
            subscription.sync_from_stripe_data(subscription.api_retrieve())

    if subscription_holder.has_active_subscription():
        subscription_name = get_product_and_metadata_for_subscription(
            subscription_holder.active_stripe_subscription
        ).metadata.name
        messages.success(request, f"You've successfully signed up for {subscription_name}. "
                                  "Thanks so much for the support!")
        # notify admins when someone signs up
        mail_admins(
            subject=f"Hooray! Someone just signed up for a {subscription_name} subscription!",
            message="Email: {}".format(request.user.email),
            fail_silently=True,
        )
    
    assert isinstance(subscription_holder, Team)
    redirect = reverse('subscriptions:team_subscription_details', args=[subscription_holder.slug])
    
    return HttpResponseRedirect(redirect)


@login_required
@require_POST
@catch_stripe_errors
@transaction.atomic
def create_customer(request, subscription_holder=None):
    """
    Create a Stripe Customer and Subscription object and map them onto the subscription_holder

    Expects the inbound POST data to look something like this:
    {
        'email': 'cory@example.com',
        'userId': '23',
        'payment_method': 'pm_1GGgZaIYTEadrA0y0tthZ5UH'
    }
    """
    subscription_holder = subscription_holder if subscription_holder else request.user
    request_body = json.loads(request.body.decode('utf-8'))
    user_id = int(request_body['user_id'])
    email = request_body['user_email']
    assert request.user.id == user_id
    assert request.user.email == email

    assert isinstance(subscription_holder, Team)
    team_id = int(request_body['team_id'])
    assert request.team.id == team_id
    
    payment_method = request_body['payment_method']
    plan_id = request_body['plan_id']
    stripe.api_key = djstripe_settings.STRIPE_SECRET_KEY

    # first sync payment method to local DB to workaround https://github.com/dj-stripe/dj-stripe/issues/1125
    payment_method_obj = stripe.PaymentMethod.retrieve(payment_method)
    djstripe.models.PaymentMethod.sync_from_stripe_data(payment_method_obj)

    # create customer objects
    # This creates a new Customer in stripe and attaches the default PaymentMethod in one API call.
    customer = stripe.Customer.create(
      payment_method=payment_method,
      email=email,
      invoice_settings={
        'default_payment_method': payment_method,
      },
    )

    djstripe_customer = djstripe.models.Customer.sync_from_stripe_data(customer)

    # create subscription
    subscription = stripe.Subscription.create(
      customer=customer.id,
      items=[
        {
          'plan': plan_id,
        },
      ],
      expand=['latest_invoice.payment_intent'],
    )
    djstripe_subscription = djstripe.models.Subscription.sync_from_stripe_data(subscription)

    # customer always is associated with the user
    request.user.customer = djstripe_customer

    subscription_holder.subscription = djstripe_subscription
    if subscription_holder != request.user:
        subscription_holder.save()

    request.user.save()

    data = {
        'customer': customer,
        'subscription': subscription
    }
    return JsonResponse(
        data=data,
    )

def _get_subscription_urls(subscription_holder):
    # get URLs for subscription helpers
    url_bases = [
        'subscription_details',
        'create_customer',
        'subscription_success',
        'subscription_demo',
        'subscription_gated_page',
    ]

    def _construct_url(base):
        return reverse(f'subscriptions:team_{base}', args=[subscription_holder.slug])
        

    return {
        url_base: _construct_url(url_base) for url_base in url_bases
    }


@login_required
def subscription_demo(request, subscription_holder=None):
    subscription_holder = subscription_holder if subscription_holder else request.user
    return render(request, 'subscriptions/demo.html', {
        'active_tab': 'subscription_demo',
        'subscription': subscription_holder.active_stripe_subscription,
        'product': get_product_and_metadata_for_subscription(
            subscription_holder.active_stripe_subscription
        ),

illumidesk/teams/views.py
from rest_framework import viewsets

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from illumidesk.teams.decorators import login_and_team_required
from illumidesk.teams.invitations import send_invitation

from .forms import TeamChangeForm
from .models import Invitation
from .models import Team
from .serializers import InvitationSerializer
from .serializers import TeamSerializer


@login_required
def manage_teams(request):
    return render(request, 'teams/teams.html', {})


@login_required
def list_teams(request):
    teams = request.user.teams.all()
    return render(request, 'teams/list_teams.html', {
        'teams': teams,
    })


@login_required
def create_team(request):
    if request.method == 'POST':
        form = TeamChangeForm(request.POST)
        if form.is_valid():
            team = form.save()
            team.members.add(request.user, through_defaults={'role': 'admin'})
            team.save()
            return HttpResponseRedirect(reverse('teams:list_teams'))
    else:
        form = TeamChangeForm()
    return render(request, 'teams/manage_team.html', {
        'form': form,
        'create': True,
    })


@login_and_team_required
def manage_team(request, team_slug):
    team = request.team
    if request.method == 'POST':
        form = TeamChangeForm(request.POST, instance=team)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teams:list_teams'))
    else:
        form = TeamChangeForm(instance=team)
    return render(request, 'teams/manage_team.html', {
        'team': team,
        'form': form,
    })


def accept_invitation(request, invitation_id):
    invitation = get_object_or_404(Invitation, id=invitation_id)
    return render(request, 'teams/accept_invite.html', {
        'invitation': invitation,
    })


class TeamViewSet(viewsets.ModelViewSet):
    queryset = Team.objects.all()
    serializer_class = TeamSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.teams.all()

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        team = serializer.save()
        team.members.add(self.request.user, through_defaults={'role': 'admin'})


class InvitationViewSet(viewsets.ModelViewSet):
    queryset = Invitation.objects.all()
    serializer_class = InvitationSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.queryset.filter(team__in=self.request.user.teams.all())

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        invitation = serializer.save(invited_by=self.request.user)
        send_invitation(invitation)

illumidesk/templates/web/components/app_nav.html
<aside class="menu">
  <p class="menu-label is-hidden-tablet-only">
    Application
  </p>
  <ul class="menu-list">
      <li>
          <a href="{% url 'web:home' %}" {% if active_tab == 'dashboard' %}class="is-active"{% endif %}>
              <span class="icon"><i class="fa fa-home"></i></span><span class="is-hidden-tablet-only">Dashboard</span>
          </a>
      </li>


    {% include "web/components/team_nav.html" %}


  </ul>
  <p class="menu-label is-hidden-tablet-only">
    My Account
  </p>
  <ul class="menu-list">


    <li>
        <a href="{% url 'users:user_profile' %}" {% if active_tab == 'profile' %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-user"></i></span><span class="is-hidden-tablet-only">Profile</span>
        </a>
    </li>
    <li>
        <a href="{% url 'account_change_password' %}" {% if 'accounts/password/change' in request.path %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-unlock-alt"></i></span><span class="is-hidden-tablet-only">Change Password</span>
        </a>
    </li>
    <li>
        <a href="{% url 'account_logout' %}" {% if 'accounts/logout' in request.path %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-sign-out"></i></span><span class="is-hidden-tablet-only">Sign out</span>
        </a>
    </li>
  </ul>


  <p class="menu-label is-hidden-tablet-only">
    Teams
  </p>
  <ul class="menu-list">
    <li>
        <a href="{% url 'teams:manage_teams' %}" {% if 'teams' in request.path %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-group"></i></span><span class="is-hidden-tablet-only">Teams</span>
        </a>
    </li>
  </ul>


</aside>

illumidesk/templates/web/components/footer.html
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      {{project_meta.NAME}} &mdash; Copyright <span id="copyright-year">2019</span>
    </p>
  </div>
</footer>
<script>
    document.getElementById('copyright-year').innerText = (new Date()).getFullYear();
</script>

illumidesk/templates/web/components/team_nav.html
{% load meta_tags %}
{% if request.team and request.user|is_admin_of:request.team %}
  <li>
      <a href="{% url 'web:team_admin' request.team.slug %}" {% if active_tab == 'team-admin' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-gear"></i></span><span class="is-hidden-tablet-only">Admin</span>
      </a>
  </li>


  <li>
      <a href="{% url 'subscriptions:team_subscription_demo' request.team.slug %}" {% if active_tab == 'subscription_demo' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-desktop"></i></span><span class="is-hidden-tablet-only">Subscription Demo</span>
      </a>
  </li>
  <li>
      <a href="{% url 'subscriptions:team_subscription_details' request.team.slug %}" {% if active_tab == 'subscription' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-repeat"></i></span><span class="is-hidden-tablet-only">Subscription</span>
      </a>
  </li>


{% endif %}

illumidesk/templates/web/components/top_nav.html
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="nav-menu">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="nav-menu">
        <div class="navbar-start">
            <a class="navbar-item {% if request.path == '/' %}is-active{% endif %}" href="{% url 'web:home' %}">
                {{project_meta.NAME}}
            </a>
        </div>
        <div class="navbar-end">
          {% if user.is_authenticated %}
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <img class="avatar is-hidden-touch" src="{{ user.avatar_url}}">
                <span class="is-hidden-desktop">My Account</span>
              </a>
              <div class="navbar-dropdown is-right">
                <a class="navbar-item" href="{% url 'users:user_profile' %}" >
                  <span class="icon"><i class="fa fa-user"></i></span><span>Profile</span>
                </a>
                <a class="navbar-item" href="{% url 'account_change_password' %}">
                  <span class="icon"><i class="fa fa-unlock-alt"></i></span><span>Change Password</span>
                </a>
                <a class="navbar-item" href="{% url 'account_logout' %}" >
                  <span class="icon"><i class="fa fa-sign-out"></i></span><span>Sign out</span>
                </a>
              </div>
            </div>
          {% else %}
              <div class="navbar-item">
                  <div class="buttons">
                      <a class="button is-primary is-outlined" href="{% url 'account_signup' %}">Sign up</a>
                      <a class="button is-text" href="{% url 'account_login' %}">Sign in</a>
                  </div>
              </div>
          {% endif %}
        </div>
      </div>
    </div>
</nav>